### ISSUE TITLE
Yosemite

### ISSUE THREAD

**Issue by diazgilberto** [AndrewHazelden/More-TextWrangler-and-BBEdit-Color-Schemes#2]
TextWrangler doesn't look at that path for Color Schemes.

**Comment by AndrewHazelden** [comment]
The Color Schemes folder doesn't exist by default when you first install and run TextWrangler. You can create it manually using the instructions that come with the download. I have used this module successfully with Mac OS X 10.6 to 10.10 so I know it does work.

One way to create the folders is to use the terminal program and run the command:
  mkdir -p ~/"Library/Application Support/TextWrangler/Color Schemes/"

You can also go to the TextWrangler preferences window and open up the Text Colors section. If you modify the color settings and save a new preset, the Color Schemes folder will also be created for you.

Regards,
Andrew
